src/espresso/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include('homepage.urls')),    
    path('parchment_intake/', include('parchment_intake.urls')),
    path('green_beans_intake/', include('green_beans_intake.urls')),
    path('beans_intake/', include('beans_intake.urls')),
    path('dry_coffee/', include('dry_coffee.urls')),    
    path('reports/', include('reports.urls')),    
    path('hull_grade/', include('hull_grade.urls')),    
    path('admin/', admin.site.urls),
]

src/haul_grade/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='haul_grade_index'),
    # path('<str:batch_status>/', views.get_batch_with_status, name='get_batch_list'),
    # path('<str:batch_status>/<int:intake_id>/', views.get_intake_details, name='report_intake_details'),
]

src/reports/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='report_index'),
    path('<str:batch_status>/', views.get_batch_with_status, name='get_batch_list'),
    path('<str:batch_status>/<int:intake_id>/', views.get_intake_details, name='report_intake_details'),

]

src/green_beans_intake/models.py
from django.db import models
from beans_intake.models import Supplier, Employee
from django.utils import timezone
from jsignature.fields import JSignatureField


# Create your models here.
class GreenBeansIntake(models.Model):
    INTAKE_TYPE = (
        ('S',  'Hulled, graded and sorted'),
        ('N', 'Hulled, graded NOT sorted'),
    )

    supervisor = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)
    
    moisture_content = models.FloatField(default=0.00)  
    intake_type = models.CharField(max_length=1, choices=INTAKE_TYPE)

    grade1_weight = models.FloatField(default=0.00) 
    grade2_weight = models.FloatField(default=0.00) 
    grade3_weight = models.FloatField(default=0.00) 
    grade_pb_weight = models.FloatField(default=0.00) 
    grade_fines_weight = models.FloatField(default=0.00) 

    resting_period = models.IntegerField()
    
    supervisor_signature = JSignatureField(null=True, blank=True)
    
    delivery_person_name = models.CharField(max_length=60, null=True, blank=True)
    delivery_person_signature = JSignatureField(null=True, blank=True)

    created_date = models.DateField(default=timezone.now)

    signed_delivery_slip = models.FileField(upload_to=f'delivery-slips')
    delivery_person_pic = models.FileField(upload_to=f'delivery-persons')

    marker_placed = models.BooleanField(default=False)
    intake_note = models.TextField(null=True, blank=True)

    def _str__(self):
        return str(self.id)


class GreenBeansIntakeFiles(models.Model):
    intake = models.ForeignKey(GreenBeansIntake, on_delete=models.CASCADE)
    proof_file = models.FileField(upload_to=f'green-beans-intake-files')

    def __str__(self):
        return str(self.proof_file)

src/haul_grade/templates/haul_grade/index.html
{% extends "homepage/base_template.html" %}


{% block content %}
 <h1> Hauling and Grading  </h1>

<p>&nbsp;</p>
<h3>Batches from Cherry Intake</h3>
 
<table class="table">
    <thead>
    <tr>
        <th> Intake ID </th>
        
        <th>  Location </th>

        <th>  Full Bags  </th>

        <th>  Partial Bag Weight </th>

        <th>Intake Date</th>

    </tr>
    </thead>
    <tbody>
    {% for item in inventory %}
    <tr> 
        <td><a href="{{ item.intake.id }}"> {{item.id}}  </a></td> 
        
        <td>{{ item.intake.lot_location }}</td>

        <td>{{ item.full_bags  }}</td>

        
        <td>{{ item.partial_bag_weight }}</td>
      

        <td>{{ item.created_date }}</td>
    
    </tr>
    {% endfor %}
    </tbody>
</table>

<p>&nbsp;</p>
<h3>Batches from Parchment Intake</h3>

<table class="table">
    <thead>
        <tr>
            <th> Intake ID </th>
            
            <th>  Supplier </th>
    
            <th>  resting_period </th>
    
            <th>  Full Bags  </th>
    
            <th>  Partial Bag Weight </th>
    
            <th>Intake Date</th>
    
        </tr>
        </thead>
        <tbody>
        {% for item in parchments %}
        <tr> 
            <td><a href="{{ item.id }}"> {{item.id}}  </a></td> 
            
            <td>{{ item.supplier }}</td>
    
            <td>{{ item.resting_period }}</td>
    
            <td>{{ item.total_bags_count  }}</td>
            
            <td>{{ item.total_weight }}</td>
    
            <td>{{ item.created_date }}</td>
        
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>&nbsp;</p>
<h3>Batches from Green Beans Intake</h3>

<table class="table">
    <thead>
    <tr>
        <th> Intake ID </th>
        
        <th>  Supplier </th>

        <th>  resting_period </th>

        <th>  Intake Type  </th>

        <th>  GR1|GR2|GR3|GRPB|GRF </th>

        <th>Intake Date</th>

    </tr>
    </thead>
    <tbody>
    {% for item in green_beans %}
    <tr> 
        <td><a href="{{ item.id }}"> {{item.id}}  </a></td> 
        
        <td>{{ item.supplier }}</td>

        <td>{{ item.resting_period }}</td>

        <td>{{ item.get_intake_type_display  }}</td>
        
        <td>{{ item.grade1_weight }} | {{ item.grade2_weight }} | {{ item.grade3_weight }} 

            {{ item.grade_pb_weight }} | {{ item.grade_fines_weight }}


        </td>

        <td>{{ item.created_date }}</td>
    
    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock %}